### ISSUE TITLE
texture.render throws Error: WebGL: texImage2D: null ImageData

### ISSUE THREAD

**Issue by valueerrorx** [photonstorm/phaser#1310]
the according line in phaser.js is :

    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);

the following example was used to trigger this error (only with webgl enabled - canvas works fine)

    texture = new PIXI.RenderTexture(game.width, game.height, game.renderer);
    matrix = new PIXI.Matrix();
    matrix.translate(-game.camera.x, -game.camera.y);
    texture.render(game.world, matrix);

the error can also be seen if using phaser methods

**Comment by amadeus** [comment]
I've run into what I believe is a very similar issue. However, upon further research, I am not sure whether it is a Pixi bug, as I can't seem to isolate it in Pixi, only in Phaser. But I could easily be missing something. Safari (both desktop and iOS seem to produce this bug, Chrome does not exhibit any problems:

This example uses PixiJS, and there doesn't appear to be any problems with RenderTexture in Safari, Firefox, or Chrome:
http://jsfiddle.net/amadeus/rL3Lvjxr/

However, if I do a similar thing in Phaser, I get the aforementioned `Type Error` in Safari:
http://jsfiddle.net/amadeus/taug8maq/

The error appears to be due to `texture.source` being undefined. `texture` exists, but `texture.source` does not.

By simply changing the line in the method `PIXI.WebGLRenderer.prototype.updateTexture` in pixi.js:

```js
gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);
```

to:

```js
if (texture.source) {
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, texture.source);
}
```

Appears to fix the problem. However, it's a change in Pixi, and Pixi does not seem to exhibit the bug on it's own, so there must be something additional that Phaser is doing that I am unaware of that could trigger this case.

**Comment by photonstorm** [comment]
This bug is specific to the version of IE11 being used. In short it means you're using an older version of IE11 that doesn't support UNSIGNED_BYTE. This is fixed in the current public release of IE11.

There's no (known) clean way to detect this automatically, and it won't be done by Pixi either  (https://github.com/GoodBoyDigital/pixi.js/issues/1383) so I'm reluctantly closing this off.

**Comment by emuvente** [comment]
I don't believe that this is a UNSIGNED_BYTE support issue. The bug is that texture.source is undefined in the call to gl.texImage2D as noted by @amadeus . 
Chrome does not treat this as an error. Firefox reports an error but otherwise has the desired behavior. The current version of IE (11.0.9600) does treat this as an error and does not produce the desired behavior.
If this was an UNSIGNED_BYTE support issue, then the current version of IE11 would not still be producing the bug when running the test cases described above.

**Comment by photonstorm** [comment]
You're right. I've dug a little deeper and it's because Sprite and Image were both calling `updateTexture` on the RenderTexture. Pixi has no guards in place against this, hence the errors in IE/Safari. So I've stopped both object types from calling updateTexture at all if they're using a RenderTexture. This appears to have solved this issue, along with a few others actually.

**Comment by amadeus** [comment]
@photonstorm Awesome! Thanks for the fix!

**Comment by DarkRaziel** [comment]
I was testing this fix in safari and it will still crash if Sprite.loadTexture receives a PIXI.RenderTexture. Someone should look into that.

I reproduced the error by generating a texture from a group using Group.generateTexture();

**Comment by tfsJoe** [comment]
I saw this issue resurface while using a video texture, in both 2.6.2 and 2.13.2. I got around it by adding an extra check for null at line 11816 of phaser.js, in `PIXI.WebGLRenderer.prototype.updateTexture`

```{
    if (!texture.hasLoaded || !texture.source)
    {
        return false;
    }
//...```

**Comment by photonstorm** [comment]
@tfsJoe this issue is 4 years old, your comment would be far better placed on the Phaser CE repo.
