### ISSUE TITLE
Tint isn't working for sprites

### ISSUE THREAD

**Issue by nkholski** [photonstorm/phaser#3262]
I noticed that tint isn't working for sprites on a build from this morning. IDK if we should submit issues for builds from github, but if you're aware you could just close the issue.

**Comment by photonstorm** [comment]
We fixed tint in the renderer yesterday, so a fresh build from this morning should work fine. I just tested it with the display / tint examples and they're all looking correct now (where-as with 3.1.0 they did not). Unless you tried tinting something specific not covered by the examples that wasn't updated properly?

**Comment by nkholski** [comment]
I reinstalled Phaser and it works now. I don't know if I made a mistake before or something was fixed, but the issue is gone. Sorry. Closing the issue.

**Comment by photonstorm** [comment]
No worries, thanks for taking the time to open it.

**Comment by nkholski** [comment]
Ok. Now I got it. I ran it in canvas-mode. Tint is still broken for canvas for the current github version. It works fine in WebGL though.

**Comment by photonstorm** [comment]
Tint isn't supported for Canvas, so this is correct.

**Comment by nkholski** [comment]
Ok. Let's close this miserable issue again :-)
