### ISSUE TITLE
Multitasking on iOS breaks input

### ISSUE THREAD

**Issue by sftsk** [photonstorm/phaser#3756]
I just noticed there is a problem on the iPad when swiping up the "dock" from the button.
Once you swipe up the dock and go back to the app it does not take input events anymore.

You can try it out in this example: http://labs.phaser.io/view.html?src=src\input\game%20object\on%20down%20event.js

In Safari on the iPad it seems to lose the input manager when the dock slides in.

It seems to be ok with the multi-touch examples: http://labs.phaser.io/index.html?dir=input/multitouch/

Anybody noticed this? Any idea what might go wrong? JS console is not throwing any errors..

**Comment by samme** [comment]
Try (from a scene)

    this.input.manager.touch.capture = false;

**Comment by sftsk** [comment]
Sorry for only getting back at this now, didn't have access to my iPad for some time.

Thank you @samme , this solves the issue.

Will this line of code have any downsides/ create other problems?

**Comment by sftsk** [comment]
After trying it out setting `this.input.manager.touch.capture = false;` creates a lot of new problems. I don't think this is a solution.

When that's set you can zoom within the screen, clicks don't really work anymore and you can scroll around.

**Comment by sachinhosmani** [comment]
This is reproducible with FBInstant's APIs such as `chooseAsync()` which takes away control from the game. Upon closing it, I find problems with Phaser listening to inputs again. Per my observation, after you close FB's invite dialog, the game remains stuck for about a second before looping normally. If you press during this "stuck" phase input stops working. I find this problem only on iPhone.

I tried this as a workaround (as per @samme 's suggestion), but it didn't work.

`// Whether invite is completed
var chosenContext = false;

// Handles invite button clicks
function inviteBtnHandler() {
  // Disable inputs
  this.input.manager.touch.capture = false;
  // This is when control goes away from the game
  FBInstant.context.chooseAsync().then(function() {
    chosenContext = true;
  }).then(function() {
    chosenContext = true;
  });
}

function update() {
  if (chosenContext) {
    // control resumed
    chosenContext = false;
   // enable inputs
    this.input.manager.touch.capture = true;
  }
  // rest of stuff
}`

**Comment by photonstorm** [comment]
Looking into this further. I just tried the latest Phaser build (3.13 Beta 1) in Safari on an iPad still running iOS 11. I loaded the example, pressed the sprite a few times and it reacted normally. I swiped the dock up and then pressed the sprite again, while the dock was still visible, and the dock vanished and the sprite re-acted normally. I tried pulling down the Notifications panel, putting it away, taping the Sprite, it still worked. 

Either this was inadvertently fixed via other updates in the Input Manager recently, or there's another way of triggering it?

**Comment by photonstorm** [comment]
Closing this issue as the related one is confirmed fixed and this can no longer be reproduced in current versions.

**Comment by sftsk** [comment]
I have just tried it again and it still does not work. I am on an iPad Pro 9,7" with iOS 12.
I open the app, all works fine. I slide in the dock from the bottom, I close the dock -> the app gets no input anymore.

The problem doesn't happen with the notification panel. I guess it has to do with iOS multitasking and the app somehow loosing "focus" for a moment so the input manager gets stuck in the wrong state.
Maybe a started swipe that newer ends..

I really hope you can sort this out.

**Comment by photonstorm** [comment]
@sftsk I can't sort it unless I can reproduce it, and doing exactly the same process as you doesn't trigger it for me (I can upload a video if you like?).

Which makes me think it's something else. A combination of the code in the Scene plus this happening maybe. Maybe the resize event firing together with input?!

**Comment by kooappsdevs** [comment]
Hi @photonstorm & @sftsk,

I had the same issue. What's weird is that there was a time frame where tapping after showing and hiding the dock just worked perfectly for around 30 minutes until it just stopped working again so I needed to find and fix it anyway.
 
The issue is that apparently, iOS devices calls 'touchcancel' when you bring up the dock and I noticed the touchmanager had no handling for the touchcancel event so I just added the touchcancel methods to the already existing TouchManager listeners and had it call the TouchEnd events (which I think is ultimately not an elegant fix at all since doing this would perform unwanted events like tapping on a gameobject while you are swiping the dock).

This can probably be reproduced by adding an image with pointerup/pointerdown events right above the menu button of the iphone/ipad (Not sure if swiping the dock would trigger the button start events queue - though I'm not sure why input is lost while this is done though.) I hope this helps debug the issue and apply a better fix to it.

**Comment by photonstorm** [comment]
"30 minutes" ?!

I have tried to replicate this so many times now. I'll try once more with an image around the hot areas of the screen. I just have no idea why I can't make this happen in any of my iOS devices. It's extremely frustrating.

**Comment by photonstorm** [comment]
Ok, after a bunch of trial and error I'm pretty sure this is resolved now. I've uploaded Beta 1 to the master branch and would appreciate it if anyone here could test it. I've attached a build file as well if you need that.  Note, this has the new Scale Manager in, which means game resizing is disabled in this build - hopefully, it won't stop you being able to test it.
[dev.zip](https://github.com/photonstorm/phaser/files/2482630/dev.zip)

**Comment by sftsk** [comment]
Hello, I have just managed to test this out. The bug doesn't happen anymore, amazing work!!!

Thank you so much :)

**Comment by Arencia** [comment]
Hi,

I think this issue has made its way back into Phaser since version 3.16.x. I had the same problem while developing something on 3.17.0 but I had to go back to 3.15.1 because of this.

This was tested on an iPad Pro (11-inch) on iOS 12.2 with the [same example](http://labs.phaser.io/view.html?src=src\input\game%20object\on%20down%20event.js) from the initial issue.
Example gif: https://imgur.com/a/IGdl2N1

**Comment by photonstorm** [comment]
@Arencia this is fixed in master branch (3.18)

**Comment by Robominister** [comment]
I apologize for asking this on a closed ticket: however, i am trying to apply some fixes to some legacy games (using phaser 2 ce), and i wondered if anyone here knows if an equivalent fix (to this same issue) was applied there ?

**Comment by photonstorm** [comment]
@Robominister you'd be better off asking this directly on the Phaser 2 CE repo as an issue (or checking the source there first perhaps?) - it wasn't added by me, but that doesn't mean it wasn't added.

**Comment by Robominister** [comment]
@photonstorm ok thanks for the quick reply, i will do that

**Comment by zhekich-an** [comment]
> Try (from a scene)
> 
> ```
> this.input.manager.touch.capture = false;
> ```

Дякую, дай Боже тобі здоров'ячка!
