### ISSUE TITLE
Tilemap and sprite lighting is broken

### ISSUE THREAD

**Issue by imilo** [photonstorm/phaser#3949]
## Version

* Phaser Version: v3.12.0-beta2
* Operating system: Linux

## Description

While learning lights in Phaser I've noticed problems with tilemap's dynamic layer and sprites when I enable lights:
1. Sprite becomes invisible
2. Dynamic layer not working at all (JS errors in a console)

## Example Test Code

Here is an example code, which is a modified version of `https://labs.phaser.io/edit.html?src=src/game%20objects/tilemap/dynamic/light%20map.js` (you can just copy it there and run):

```javascript
var config = {
    type: Phaser.AUTO,
    width: 800,
    height: 600,
    parent: 'phaser-example',
    backgroundColor: '#333333',
    scene: {
        preload: preload,
        create: create,
        update: update
    }
};

var light;
var player;
var layer;

var game = new Phaser.Game(config);

function preload ()
{
    this.load.image('tiles', [ 'assets/tilemaps/tiles/drawtiles1.png', 'assets/tilemaps/tiles/drawtiles1_n.png' ]);
    this.load.spritesheet('dude', ['src/games/firstgame/assets/dude.png', 'src/games/firstgame/assets/dude.png'], { frameWidth: 32, frameHeight: 48 });

    this.load.tilemapCSV('map', 'assets/tilemaps/csv/grid.csv');
}

function create ()
{
    var map = this.make.tilemap({ key: 'map', tileWidth: 32, tileHeight: 32 });

    var tileset = map.addTilesetImage('tiles', null, 32, 32, 1, 2);
    layer = map.createDynamicLayer(0, tileset, 0, 0);
    player = this.add.sprite(48, 40, 'dude');

    // player.setPipeline('Light2D');
    // layer.setPipeline('Light2D');

    // this.lights.enable().setAmbientColor(0xffffff);
    // this.lights.addLight(100, 100, 100).setColor(0xff0000).setIntensity(3.0);
}

function update (){}
```
At this moment it is a working state without lights - tilemap is visible, sprite too, no errors in a console. But:
1. Uncomment lines **37, 40, 41** - player's sprite disappears.
2. Uncomment lines **37 - 41** - example is not working at all, two Javascript errors is the console:
```
WebGLPipeline.js:345 WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range
```
```
ForwardDiffuseLightPipeline.js:520 Uncaught TypeError: this.batchVertices is not a function
    at ForwardDiffuseLightPipeline.batchTexture (VM164 dev.js:132599)
    at DynamicTilemapLayerWebGLRenderer [as renderWebGL] (VM164 dev.js:157931)
    at WebGLRenderer.render (VM164 dev.js:131363)
    at CameraManager.render (VM164 dev.js:11713)
    at Systems.render (VM164 dev.js:138337)
    at SceneManager.render (VM164 dev.js:135910)
    at Game.step (VM164 dev.js:6657)
    at TimeStep.step (VM164 dev.js:7765)
    at step (VM164 dev.js:26793)
```
Firefox 1'st error's description is a little more informative:
```
Error: WebGL warning: disableVertexAttribArray: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
```

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by imilo** [comment]
Unfortunately in **v3.12.0-beta3** there are still errors. If I uncomment all lines from the example test code in the first post I get several problems:

1. Sprite is still invisible, although light source's radius is good enough;
2. Console error `WebGL: INVALID_VALUE: disableVertexAttribArray: index out of range` still exists. Line `gl.disableVertexAttribArray(location);` from **WebGLPipeline.js**. This error is produced by `layer.setPipeline('Light2D')`;
3. Texture key error: `Texture key already in use: dude`

Can you re-open this issue?!
